### ISSUE TITLE
No longer maintained - Looking for maintainers

### ISSUE THREAD

**Issue by tqwewe** [tqwewe/prettier-plugin-tailwind#46]
Hi 👋 
I made this project a little while ago and it seemed to get a whole lot more attention than expected!
Unfortunately I've been busy working with Rust in the world of backend systems and haven't spent much time on frontend, and therefore haven't had time to maintain this project.

For the sake of everyone waiting for issues to be resolved and support for updates to prettier & tailwind, **I am looking for maintainers.**

**If you have time and are willing to help out with this project, please get in touch here and I'll happy add you as a maintainer.**

Prettier hasn't added official support for plugins like this one, so the implementation is a little hacky and not ideal. I was waiting for prettier to eventually add support for overriding but it doesn't seem to be a priority for them sadly. See issue https://github.com/prettier/prettier/issues/4424.

_On a side note, I apologise to the issues I may have missed or forgot to reply to, and I hope you understand 🙏_

**Comment by MichaelDeBoey** [comment]
@tqwewe @tailwindcss now has an official Prettier plugin: [`prettier-plugin-tailwind`](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Comment by tqwewe** [comment]
Yep I just saw this! It's a bit of a relief now, I felt bad from having lack of time to maintain this project.
I'll add a link to the official one on this repo's README shortly.

**Comment by mryechkin** [comment]
@tqwewe thank you for maintaining it this far! It's been a life-saver

**Comment by AucaCoyan** [comment]
Hello @tqwewe! Can I ask you to archive the repo and deprecate the npm package?
I tripped this morning by typing
```console
npm install -D prettier prettier-plugin-tailwind
```
instead of the official

```console
npm install -D prettier prettier-plugin-tailwindcss
```
(`css` at the end)
I think maybe more people make mistakes by ommiting the `css`, and it would be great if this package is not installable anymore. What do you think?
